version: '3.8'

services:
  mysql:
    command: --default_authentication_plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: tviology_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: rootpassword
      MYSQL_USER: tv_user
      MYSQL_DATABASE: tv_app
    image: mysql:8.0.21
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: tviology_redis
    volumes:
      - ./redis_data:/redis_data
    ports:
      - '6379:6379'
  web:
    build: .
    container_name: tviology_web
    ports:
      - '8000:8000'
    volumes:
      - .:/app/tviology  # set base reference point for container source:target
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1 # set zero for production
      - SECRET_KEY=dummy_secret_key # add proper key for production
      - ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0 # add website/ip for production
      - REDIS_URL=redis://localhost
    depends_on:
      - mysql
      - redis
volumes:
  mysql_data: